# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=250)),
                ('person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('byn', models.FloatField(null=True)),
                ('byr', models.IntegerField(null=True)),
                ('comment', models.CharField(max_length=1000000)),
            ],
        ),
    ]
